rol.getAll=select * from rol where true
rol.findById=select * from rol where id=? limit 1
rol.insert=INSERT INTO public.rol(nombre,permisos) VALUES (?,?)
rol.update=update rol set nombre=?, permisos=? where id=?
rol.delete=delete from rol where id=?