cliente.getAll=select * from cliente where true
cliente.findById=select * from cliente where id=? limit 1
cliente.insert=insert into cliente (nombres, apellidos, ci_ruc, email, telefono) VALUES (?, ?, ?, ?, ?)
cliente.update=update cliente set nombres=?, apellidos=?, ci_ruc=?, email=?, telefono=? where id=?
cliente.delete=delete from public.cliente c where c.id = ?