cliente.getAll=select * from cliente where true
cliente.findById=select * from cliente where id=? limit 1
cliente.insert=INSERT INTO public.cliente(apellidos, nombres, ruc_ci, telefono) VALUES (?, ?, ?, ?)
cliente.update=UPDATE public.cliente SET 
cliente.delete=delete from public.cliente c where c.id = ?