spring.application.name=sysfact

# Configuracion del Datasource
spring.datasource.jdbc-url=jdbc:postgresql://localhost:5432/sysfact
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.session.jdbc.initialize-schema=always

# Enable multipart uploads
spring.servlet.multipart.enabled = true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold = 2KB
# Max file size.
spring.servlet.multipart.max-file-size = 200MB
# Max Request Size
spring.servlet.multipart.max-request-size = 215MB

# Log write to console
logging.level.com.marithe.sysfact = debug
logging.level.root = info
logging.level.org.springframework.web = info
logging.pattern.console = %d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

# Log JDBC queries
logging.level.org.springframework.jdbc.core = trace
server.servlet.context-path=/sysfact

# File Storage Properties
# All files uploaded through the REST API will be stored in this directory
#file.upload-dir=/opt/public
#file.upload-dir=/home/alcides/repo/ventas-jdbc/files
#file.report-dir=/home/alcides/repo/entas-jdbc/reports