sector.getAll=select * from sector where true 
sector.findById=select p.id, p.nombre from sector p where id=? limit 1
sector.insert=insert into sector(nombre) values(?)
sector.update=update sector set nombre=? where id=? 
sector.delete=delete from sector where id=?