parametro.getAll=select * from parametros where activo=true
parametro.findByCodigo=select p.id, p.descripcion, p.codigo, p.activo, p.valor from parametros p where p.codigo=? and p.activo=true limit 1
