parametro.getAll=select * from parametros
parametro.findByCodigo=select p.id, p.descripcion, p.codigo, p.activo, p.valor from parametros p where p.codigo=? and p.activo=true limit 1
parametro.findById=select p.id, p.descripcion, p.codigo, p.activo, p.valor from parametros p where p.id=? and p.activo=true limit 1